version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️ Dep"

  # Maintain dependencies for poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ Dep"

  # Maintain dependencies for pip
  #- package-ecosystem: "pip"
  #  directory: "/.requirements/"
  #  schedule:
  #    interval: "weekly"
  #  commit-message:
  #    prefix: "⬆️ Dep"
      
