########################################
###          DEFAULT SETTINGS        ###
########################################

# Any of those settings can be changed
# by the user. To overwrite a setting, 
# create a settings.toml or load the 
# settings from .env file or vars.
# As an example, to disable the 
# talkytrend object:
# settings.toml
# [default]
# talkytrend_enabled = false

[default]
# Dynaconf settings verification
VALUE = "On Default"

# Module Enable/Disable
google_news_lang = "en"
google_news_country = "US"
google_news_base_url = 'https://news.google.com/rss'


########################################
###     END OF DEFAULT SETTINGS      ###
########################################
